configs: evb-ast2600: Disable unused loaders
The BMCs do not use EFI or the img format.

This fixes a build failure in the smbios code:

 lib/smbios.c: In function ‘smbios_write_type0’:
 lib/smbios.c:84:58: error: ‘U_BOOT_DMI_DATE’ undeclared (first use in this function)
    84 |         t->bios_release_date = smbios_add_string(t->eos, U_BOOT_DMI_DATE);
       |                                                          ^~~~~~~~~~~~~~~

Signed-off-by: Joel Stanley <joel@jms.id.au>